spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "techieemma"
    password: "tech1234#"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
   #this is optional because it is selected by default database-platform: org.hibernate.dialect.PostgreSQLDialect